### ISSUE TITLE
Species Traits

### ISSUE THREAD

**Issue by ABeardsell** [Ecosystem-Assessments/Species_Traits#2]
# Body composition
Je n'ai pas trouvé l'information pour 4 espèces. Elles sont dans la liste d'entrées manuelles identifiée "#TBD" en commentaires et "NA" pour la composition corporelle.

# Body size
L'information est complète pour l'ensemble de la liste. J'ai fait l'ajout d'entrées manuelles et les espèces qui ne se retrouve plus dans la liste ont été commentées.

# Mobility
Les espèces ont été ajoutées dans la liste via un fichier .csv (./Data/SpeciesTraits/Mobility_ManualEntry.csv). Voir la colonne "comment" dans le fichier csv (1 entrée manquante et incertitude de quelques espèces). Tentative de combiner les deux matrices à la fin du script (objet du message de warning).

# Environment
Entrées manuelles pour 12 espèces directement dans le script. Information manquante pour deux espèces (identifiées avec NA).

# Phylum
Need to merge ./Data/SpeciesTraits/Phylum_AjoutAtlantic.RData and ./Data/SpeciesTraits/Phylum.RData

# Feeding Type
Mention de "NA" pour les algues. Pour chaque entrée manuelle, si l'information pour l'espèce n'était pas disponible, on trouvera en commentaire si l'information provient d'une espèce du même genre ou de la famille. Les espèces qui ne se retrouve plus dans la liste ont été commentées. Plus spécifiquement pour le groupe des Cnidaires, vérifier s'ils sont des filtreurs sélectifs (selective filter) ou passifs.

**Comment by david-beauchesne** [comment]
J'ai adressé les commentaires directement dans la PR. Merci!
